apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30400  # You can specify a port number here or leave it for Kubernetes to assign automatically
  type: NodePort  # Expose the service through NodePort
